name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install Black
        run: pip3 install black
        
      - name: Run Black
        run: black --check .
