name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
      - name: Black Code Formatter
        run: |
          pip3 install black
          set -e
          sh -c "black . --check"
